### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by AusiMods** [Dignity-Dev/Twitter-clone#1]
Nice script :) Good to see a lack of "frameworks" .

Error / bug Report
The initial pages (ie: account,home, notification profile and status ->.php) all have an error that comes from the value "`$u_id`" that is never mentioned on these pages the error disrupts the default view of the pages by placing the error on each follow button.
The problem is seen on my windows server running php 7+ with unrestricted error reporting.
Line numbers for the error vary but can easily be found by searching for the `$u_id` value

The error can easily be resolved by replacement of
`data-profile="<?php echo $u_id; ?>"`
with
`data-profile="<?php isset($u_id) ? $u_id : $user->id; ?>"`
However that may not be correct for the needs of the script. That would be up to the developer.
Thanks.

**Comment by Dignity-Dev** [comment]
Thank you!
Issue resolved, It was a scratch development with vanilla PHP without any frameworks.
